import AppKit
import SwiftUI

// MARK: - Clipboard history (opt-in, memory only: never written to disk)

@MainActor
final class ClipboardHistory: ObservableObject {
    static let shared = ClipboardHistory()

    enum Content {
        case text(String)
        case image(NSImage)
        case files([URL])
    }

    struct Item: Identifiable {
        let id = UUID()
        let content: Content
        let appIcon: NSImage?
    }

    @Published private(set) var items: [Item] = []
    @Published var enabled: Bool = UserDefaults.standard.bool(forKey: "clipboardHistoryEnabled") {
        didSet {
            UserDefaults.standard.set(enabled, forKey: "clipboardHistoryEnabled")
            enabled ? start() : stop()
        }
    }

    // ponytail: 30 items in memory, images included; cap images separately if memory matters.
    private let limit = 30
    private var lastChange = NSPasteboard.general.changeCount
    private var poller: Task<Void, Never>?

    /// Password managers mark secrets with these (nspasteboard.org): never record them.
    private static let skipped: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    private init() {
        if enabled { start() }
    }

    private func start() {
        guard poller == nil else { return }
        lastChange = NSPasteboard.general.changeCount
        // The pasteboard has no change notification: a cheap changeCount check is the standard way.
        poller = Task { [weak self] in
            while !Task.isCancelled {
                self?.poll()
                try? await Task.sleep(nanoseconds: 750_000_000)
            }
        }
    }

    private func stop() {
        poller?.cancel()
        poller = nil
        items.removeAll()
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount
        let types = Set(pb.types ?? [])
        guard types.isDisjoint(with: Self.skipped) else { return }

        let content: Content
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            content = .files(urls)
        } else if !types.isDisjoint(with: [.png, .tiff]), let image = NSImage(pasteboard: pb) {
            content = .image(image)
        } else if let text = pb.string(forType: .string),
                  !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            content = .text(text)
        } else {
            return
        }
        insert(Item(content: content, appIcon: NSWorkspace.shared.frontmostApplication?.icon))
    }

    private func insert(_ item: Item) {
        // Same text or files copied again: move to the front instead of duplicating.
        items.removeAll { Self.sameContent($0.content, item.content) }
        items.insert(item, at: 0)
        if items.count > limit { items.removeLast(items.count - limit) }
    }

    private static func sameContent(_ a: Content, _ b: Content) -> Bool {
        switch (a, b) {
        case let (.text(x), .text(y)):   return x == y
        case let (.files(x), .files(y)): return x == y
        default:                         return false
        }
    }

    func copy(_ item: Item) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.content {
        case .text(let s):    pb.setString(s, forType: .string)
        case .image(let img): pb.writeObjects([img])
        case .files(let urls): pb.writeObjects(urls as [NSURL])
        }
        lastChange = pb.changeCount
        items.removeAll { $0.id == item.id }
        items.insert(item, at: 0)
        SoundEngine.shared.play("pop")
    }

    func remove(_ item: Item) { items.removeAll { $0.id == item.id } }
    func clear() { items.removeAll() }
}

// MARK: - Clipboard view

struct ClipboardView: View {
    @ObservedObject var state: AppState
    @ObservedObject var history = ClipboardHistory.shared
    @State private var copiedId: UUID?

    var body: some View {
        ZStack(alignment: .leading) {
            CardBackground(wash: nil)
            VStack(alignment: .leading, spacing: 6) {
                HStack(spacing: 10) {
                    Text("Clipboard")
                        .font(.system(size: 12, weight: .semibold))
                    if !history.items.isEmpty {
                        Text("\(history.items.count)")
                            .font(.system(size: 11))
                            .foregroundColor(Color(hex: "#6B7079"))
                    }
                    Spacer()
                    Toggle("Record", isOn: $history.enabled)
                        .toggleStyle(.switch)
                        .controlSize(.mini)
                        .font(.system(size: 11))
                        .foregroundColor(Color(hex: "#8E939C"))
                    if !history.items.isEmpty {
                        IconButton(icon: "trash", help: "Clear history") { history.clear() }
                    }
                }
                if !history.enabled {
                    placeholder("Turn on Record to keep what you copy. History stays in memory, passwords are skipped.")
                } else if history.items.isEmpty {
                    placeholder("Copy something: it shows up here. Click a card to copy it again.")
                } else {
                    ScrollView(.horizontal, showsIndicators: false) {
                        HStack(spacing: 6) {
                            ForEach(history.items) { item in
                                ClipCard(item: item, copied: copiedId == item.id) {
                                    history.copy(item)
                                    copiedId = item.id
                                    Task { @MainActor in
                                        try? await Task.sleep(nanoseconds: 1_200_000_000)
                                        if copiedId == item.id { copiedId = nil }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            .padding(.leading, 84)
            .padding(.trailing, 14)
            .padding(.vertical, 10)
        }
    }

    private func placeholder(_ text: String) -> some View {
        Text(text)
            .font(.system(size: 11.5))
            .foregroundColor(Color(hex: "#8E939C"))
            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .leading)
    }
}

private struct ClipCard: View {
    let item: ClipboardHistory.Item
    let copied: Bool
    let onCopy: () -> Void
    @State private var hovered = false

    var body: some View {
        ZStack(alignment: .topLeading) {
            preview
                .frame(width: 118, height: 54, alignment: .topLeading)
                .clipped()
            if copied {
                Label("Copied", systemImage: "checkmark")
                    .font(.system(size: 10.5, weight: .semibold))
                    .foregroundColor(Color(hex: "#34D399"))
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
                    .background(Color.black.opacity(0.6))
            }
        }
        .padding(6)
        .frame(width: 130, height: 66)
        .background(RoundedRectangle(cornerRadius: 10).fill(Color.white.opacity(hovered ? 0.09 : 0.04)))
        .overlay(alignment: .bottomTrailing) {
            if let icon = item.appIcon {
                Image(nsImage: icon).resizable().frame(width: 12, height: 12).padding(4)
            }
        }
        .overlay(alignment: .topTrailing) {
            if hovered {
                Button { ClipboardHistory.shared.remove(item) } label: {
                    Image(systemName: "xmark.circle.fill")
                        .font(.system(size: 11))
                        .foregroundColor(Color(hex: "#8E939C"))
                }
                .buttonStyle(.plain)
                .padding(3)
            }
        }
        .contentShape(Rectangle())
        .onHover { hovered = $0 }
        .onTapGesture(perform: onCopy)
        .help("Click to copy")
    }

    @ViewBuilder private var preview: some View {
        switch item.content {
        case .text(let s):
            Text(s.trimmingCharacters(in: .whitespacesAndNewlines))
                .font(.system(size: 10.5))
                .foregroundColor(Color(hex: "#D5D7DB"))
                .lineLimit(4)
        case .image(let img):
            Image(nsImage: img)
                .resizable()
                .aspectRatio(contentMode: .fit)
                .frame(maxWidth: .infinity, maxHeight: .infinity)
        case .files(let urls):
            HStack(spacing: 6) {
                Image(nsImage: NSWorkspace.shared.icon(forFile: urls[0].path))
                    .resizable().frame(width: 28, height: 28)
                Text(urls.count == 1 ? urls[0].lastPathComponent : "\(urls.count) files")
                    .font(.system(size: 10.5))
                    .foregroundColor(Color(hex: "#D5D7DB"))
                    .lineLimit(3)
            }
        }
    }
}
